config/routes.rb
Rails.application.routes.draw do
  get 'charges/new'

  resources :wikis
  resources :charges, only: [:new, :create, :destroy]
  resources :collaborators, only: [:create, :destroy]
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  has_many :collaborators
  has_many :wikis
  has_many :collaborations, through: :collaborators, source: :wiki
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :authentication_keys => [:login]

  # attribute for authenticating by either username or email
  attr_accessor :login

  # Allow username(s)
  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }

  # regex
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  # Change the behavior of the login action to take either usernme or email
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

  # soft deletion
  # indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end
  #make sure user account is active
  def active_for_authentication?
    super && !deleted_at
  end
  #custom message for a deleted account
  def inactive_message
  	!deleted_at ? super : :deleted_account
  end

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  has_many :collaborators
  has_many :users, through: :collaborators
  belongs_to :user, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    if current_user.premium? || current_user.admin?
      redirect_to edit_user_registration_path(current_user)
    end

    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership",
      amount: amount
    }
  end

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      description: "Blocipedia Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.stripe_id = customer.id
    current_user.update_attribute :premium, true
    current_user.update_attribute :standard, false

    flash[:notice] = "Thanks for all the money, #{current_user.username}! You are now a premium member."
    redirect_to edit_user_registration_path(current_user)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def destroy
    current_user.update_attribute :premium, false
    current_user.update_attribute :standard, true
    current_user.wikis.each { |wiki| wiki.update_attribute(:private, false) }
    flash[:notice] = "Your premium membership has been canceled."
    redirect_to edit_user_registration_path(current_user)
  end

  private

  def amount
    15_00
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @wiki = Wiki.find(params[:wiki_id])
    @user = User.where(username: params[:username]).take

    if @user == nil
      flash[:error] = "That user could not be found."
      redirect_to edit_wiki_path(@wiki)
    else
      collaborator = @wiki.collaborators.build(user_id: @user.id)
      if collaborator.save
        flash[:notice] = "#{@user.username} has been added to the wiki."
        redirect_to edit_wiki_path(@wiki)
      else
        flash[:error] = "That user could not be added. Please try again."
        redirect_to edit_wiki_path(@wiki)
      end
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    @wiki = @collaborator.wiki
    if @collaborator.destroy
      flash[:notice] = "#{@collaborator.user.username} removed as collaborator."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "#{@collaborator.user.username} could not be removed."
      redirect_to edit_wiki_path(@wiki)
    end
  end
end

app/controllers/users/registrations_controller.rb
#soft delete
class Users::RegistrationsController < Devise::RegistrationsController
  # DELETE /resource
  def destroy
    resource.soft_delete
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_flashing_format?
    yield resource if block_given?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @wikis = Wiki.all
    @user = current_user
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!
  def index
    @wikis = WikiPolicy::Scope.new(current_user, Wiki).resolve
  end

  def show
    @wiki = Wiki.find(params[:id])
    if @wiki.private?
      if @wiki.user == current_user
        wiki_path
      elsif current_user.standard?
        flash[:alert] = "You must be a premium user to view private wikis."
        redirect_to new_charge_path
      elsif @wiki.users.exclude?(current_user)
        flash[:alert] = "You must be a collaborator to view that wiki."
        redirect_to wikis_path
      end
    else
      wiki_path
    end
  end



  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_edit?
    current_user
  end

  def user_is_authorized_for_private?
    current_user.premium? || current_user.admin?
  end

  def user_is_authorized_for_collaborator_edit?
    @wiki.user || current_user.admin?
  end

  def user_is_authorized_for_delete?
    current_user.admin?
  end

  def user_has_wikis?
    @user.wikis.any?
  end

  def wiki_has_collaborators?
    @wiki.collaborators.any?
  end

  def wiki_privacy_notice(wiki)
    if wiki.private
      "PRIVATE: #{wiki.title}"
    else
      wiki.title
    end
  end

  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, {
      autolink: true,
      space_after_headers: true,
      fenced_code_blocks: true,
      disable_indented_code_blocks: true,
      highlight: true,
      footnotes: true,
      tables: true
    })
    @markdown.render(content)
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Upgrade to Premium Membership</h4>
  <p>A one-time fee of $15 will give your account life-time access to private wikis.</p>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/_edit_collaborators.html.erb
<h3>Collaborators</h3>
<% if wiki_has_collaborators? %>
  <% @wiki.collaborators.each do |collaborator| %>
    <span class="glyphicon glyphicon-user"></span>
    <%= collaborator.user.username %>
    <% if @wiki.user == current_user %>
      <%= link_to "", [collaborator], method: :delete, class: "glyphicon glyphicon-remove" %>
    <% end %>
    &nbsp;
  <% end %>
<% else %>
  <p>This wiki doesn't have any collaborators. Click the usernames below to some collaborators!</p>
<% end %>

<div class="form-group collaborators_list">
  <% @users.each do |user| %>
    <% unless user == @wiki.user || user.standard? || @wiki.collaborators.include?(user) %>
      <%= form_tag collaborators_path, class: "collaborator", method: :post do  %>
        <%= hidden_field_tag :username, user.username %>
        <%= hidden_field_tag :wiki_id, @wiki.id %>
        <%= button_tag(type: "submit", class: "button-small") do %>
          <span class="glyphicon glyphicon-ok"></span> <%= user.username %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/collaborators/_view_collaborators.html.erb
<% if wiki_has_collaborators? %>
  <% @wiki.collaborators.each do |collaborator| %>
    <span class="glyphicon glyphicon-user"></span>
    <%= collaborator.user.username %>
    &nbsp;
  <% end %>
<% else %>
  <p>This wiki doesn't have any collaborators.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %></li>
        </ul>
        <% if user_signed_in? %>
          <p class="navbar-text">Signed in as <strong><%= current_user.username %></strong></p>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          </ul>
        <% end %>
      </div>
    </nav>

    <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
    <% elsif flash[:alert] %>
        <div class="alert alert-warning" role="alert">
          <%= flash[:alert] %>
        </div>
    <% end %>

    <div class="container">

      <%= yield %>

    </div>
  </body>
</html>

app/views/welcome/_guest.html.erb
<div class="hero">
  <h3 class="text-center hero-intro">Modify, create and share wikis</h3>
  <p class="text-center"><%= link_to "Sign up", new_user_registration_path, class: "hero-button" %></p>
</div>
<div class="row">
  <div class="col-md-6">
    <h4 class="text-center">Free content encyclopedia!</h4>
  </div>
  <div class="col-md-6">
    <h4 class="text-center">Create both public and private wikis!</h4>
  </div>
</div>

app/views/welcome/_signed_in_user.html.erb
<h3 class="text-center">Hello, <%= current_user.username %>!</h3>
<hr />
<h2 class="text-center">My wikis</h2>
<% if user_has_wikis? %>
  <div class="table-responsive">
    <table class="table table-striped">
      <%= render @user.wikis %>
    </table>
  </div>
<% else %>
  <p class="text-center">You haven't created any wikis.</p>
<% end %>
<p class="text-center">
  <%= link_to "New wiki", new_wiki_path, class: "button" %>
  <%= link_to "View all wikis", wikis_path, class: "button" %>
</p>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center">Blocipedia: A collaborative community</h1>
    <% if user_signed_in? %>
      <%= render partial: 'signed_in_user' %>
    <% else %>
      <%= render partial: 'guest' %>
    <% end %>
  </div>
</div>

app/views/wikis/_form.html.erb
<%= form_for wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter new wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter new wiki information" %>
  </div>
  <% if user_is_authorized_for_private? %>
    <div class="form-group">
      <%= f.label :private, class: "checkbox" do %>
        <%= f.check_box :private %> Private wiki?
      <% end %>
    </div>
  <% end %>
  <%= f.submit "Save", class: "button-small" %>
<% end %>

app/views/wikis/_wiki.html.erb
<tr>
  <td class="text-center">
    <%= link_to wiki do %>
      <%= wiki_privacy_notice(wiki) %>
    <% end %>
  </td>
</tr>

app/views/wikis/edit.html.erb
<div class="row">
  <div class="col-md-9">
    <h1>Edit Wiki</h1>
    <%= render partial: 'form', locals: { wiki: @wiki } %>
    <% if @wiki.private? && user_is_authorized_for_collaborator_edit? %>
      <%= render partial: 'collaborators/edit_collaborators', locals: { wiki: @wiki, user: current_user } %>
    <% end %>
  </div>
  <div class="col-md-3 box-shaded">
    <h2>Markdown</h2>
    <small>
      <p># large header</p>
      <p>## medium header</p>
      <p>### small header</p>
      <p><strong>**bold**</strong></p>
      <p><em>*italic*</em></p>
      <p><mark>==highlight==</mark></p>
      <p><span style="text-decoration: line-through">~~strike through~~</span></p>
      <p>--- horizontal rule</p>
      <p>`code`</p>
      <p>Links: [linked text](https://linkurl)</p>
      <p><%= link_to "Markdown cheatsheet", "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet", class: "button-small" %><p>
    </small>
  </div>
</div>

app/views/wikis/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center">Wikis</h1>
    <div class="table-responsive">
      <table class="table table-striped">
        <%= render @wikis %>
      </table>
    </div>
    <p class="text-center"><%= link_to "New wiki", new_wiki_path, class: "button" %></p>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="row">
  <div class="col-md-9">
    <h1>New Wiki</h1>
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
  <div class="col-md-3 box-shaded">
    <h2>Markdown</h2>
    <small>
      <p># large header</p>
      <p>## medium header</p>
      <p>### small header</p>
      <p><strong>**bold**</strong></p>
      <p><em>*italic*</em></p>
      <p><mark>==highlight==</mark></p>
      <p><span style="text-decoration: line-through">~~strike through~~</span></p>
      <p>--- horizontal rule</p>
      <p>`code`</p>
      <p>Links: [linked text](https://linkurl)</p>
      <p><%= link_to "Markdown cheatsheet", "https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet", class: "button-small" %><p>
    </small>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= wiki_privacy_notice(@wiki) %></h1>
    <p><%= markdown(@wiki.body).html_safe %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-12 box-shaded">
    <h4>Creator</h4>
    <span class="glyphicon glyphicon-user"></span> <%= @wiki.user.username %>
    <% if @wiki.private? %>
      <p>&nbsp;</p>
      <h4>Collaborators</h4>
      <%= render partial: 'collaborators/view_collaborators', locals: { wiki: @wiki, user: current_user } %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <p>
      <% if user_is_authorized_for_edit? %>
        <%= link_to "Edit wiki", edit_wiki_path(@wiki), class: "button" %>
      <% end %>
      <% if user_is_authorized_for_delete? %>
        <%= link_to "Delete wiki", [@wiki], method: :delete, class: "button", data: { confirm: "Are you sure you want to delete this wiki?" } %>
      <% end %>
      <%= link_to "View my wikis", root_path, class: "button" %>
      <%= link_to "View all wikis", wikis_path, class: "button" %>
    </p>
  </div>
</div>